# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/toolboxui"
bin = "./tmp/main"
exclude_dir = ["web/node_modules"]
include_ext = ["go", "tpl", "tmpl", "html", "js", "css"]

[log]
time = true

[proxy]
enabled = false
