repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - '@commitlint/config-conventional'
          - '@commitlint/ensure'
  - repo: local
    hooks:
      - id: format-web
        name: Format TypeScript/Web code
        entry: make format-web
        language: system
        files: \.([jt]s|tsx)$
        types: [file]
        exclude: ^(node_modules/|vendor/)
        pass_filenames: false
      - id: build-web
        name: Build web assets
        entry: make build-web
        language: system
        files: \.([jt]s|tsx)$
        types: [file]
        exclude: ^(node_modules/|vendor/)
        pass_filenames: false
        always_run: true
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.2
    hooks:
      - id: go-fumpt-repo
        args: [-w]
      - id: go-imports-repo
        args: [-w]
