name: Pre-Commit Check

on:
  pull_request:

jobs:
  pre-commit:
    name: Pre-Commit Check
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 22
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.0'
    - name: Install Dependencies
      run: make deps
    - name: Run Pre-Commit
      uses: pre-commit/action@v3.0.1
